### ISSUE TITLE
all numbers in VALUES must be quoted, otherwise they are ignored

### ISSUE THREAD

**Issue by martin12333** [theproductiveprogrammer/jughead#1]
**test input**
`{"a":    1    ,"b": "2" }`

**expected output**
```
a: 1
b: 2

```
**actual output**
`b: 2
`
at

- https://observablehq.com/@martin12333/online-converter-json-to-archieml

- https://npm.runkit.com/jughead

**workaround**
`{"a":     "1"     ,"b": "2"}
`

**Comment by theproductiveprogrammer** [comment]
ArchieML only generates strings so this was the way I had originally designed it. But thinking about your point @martin12333 it seems more sensible to allow JSON to support numbers directly as well.

Have added support and pushed a fix.

Thanks @martin12333 !

**Comment by martin12333** [comment]
I have tested in the Runkit : it works. Thank you very much. I will test my Observable notebook in a few days.
