### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by brandonkal** [theproductiveprogrammer/jughead#2]
Here is some JSON that is not correctly marshalled to AML. I believe the main issue here is that the JSON keys have spaces, which is not properly handled here.

https://gist.github.com/brandonkal/b28b24d77a6500e549e8aa38a2a4d0d3

**Comment by theproductiveprogrammer** [comment]
Hi @brandonkal!

Can you provide what you feel is the expected output vs the actual? From my understanding AIML does not support keys with spaces so Jughead should not support them either. Let me know.

Thanks

**Comment by brandonkal** [comment]
As much as I dislike `throw` in JavaScript, that is likely the right approach so that there is no surprise when the AML parses back to a different object structure. Alternatively just return an error instead of a string. Ideally it would also throw if a period is in the key. Same if a boolean exists in the structure without strict mode disabled.

On the other hand, I'm looking to extend the AML parser to be more friendly
- Allow spaces in keys
- Allow `.` in keys. This may mean changing AML to use `:` to drill down instead.
- Allow string lists to start with `-`
- Comments
- Handle `{.nested}` as you would expect
- Some way to start an array without a map key i.e. `[[1,2,3]]`
- multi document

**Comment by theproductiveprogrammer** [comment]
I have added a `skipKeys` option that is set by default. When you unset it (pass `{ skipKeys: false}`) it will throw an error whenever it hits a key that it would have skipped (contains spaces, booleans, etc).

Extending the AML parser sounds brilliant. Looking forward to your enhancements.
