### ISSUE TITLE
boolean and null

### ISSUE THREAD

**Issue by brandonkal** [theproductiveprogrammer/jughead#3]
Given that AML doesn't support these types, it would be nice to see jughead convert these to strings before stringifying.

**Comment by theproductiveprogrammer** [comment]
Hi @brandonkal 

I've added a `non-strict` mode that converts booleans and nulls to strings. To activate it call:

```javascript
let archieml = jughead.archieml(obj, { strict: false })
```

I think that is a useful feature. Thanks!
